sweet: Disable display white balance
The system is attempting to initialize adaptive white balance but
fails because the expected color sensor (com.google.sensor.color)
is not available on this device, causing the following error:

DisplayPowerController[0]: failed to set up display white-balance:
java.lang.IllegalStateException: cannot find sensor com.google.sensor.color

Signed-off-by: therealmharc <therealmharc@gmail.com>